### ISSUE TITLE
Update Profile / Pull Request

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreatorProfiles#3]
Hey, I've updated my profile to handle the disenchant update you did. Cheers

In ,txt because github doesn't allow .json uploads.
[Variona-TC2016 .txt](https://github.com/NotCoffee418/TrinityCreatorProfiles/files/5571226/Variona-TC2016.txt)

**Comment by NotCoffee418** [comment]
.Is the StatsCount column being removed intentional?

**Comment by Variona** [comment]
No, it is not. I only meant to add the two new disenchant related columns. And the StatsCount column appears to remain the same on the file I uploaded.

*Edit*
I ran the two files through a difference checker and here is the result. 
[diffchecker.com/akilyYnF](https://www.diffchecker.com/akilyYnF)

So I am very confused as to what you mean

**Comment by NotCoffee418** [comment]
Whoops, yeah you're right, weird. I was a bit distracted there.
Alright thanks for the update, i've added it to the repo ^^
