### ISSUE TITLE
TrinityCore updated profile for TDB 335.23011?

### ISSUE THREAD

**Issue by LegacyAngel2K9** [NotCoffee418/TrinityCreatorProfiles#7]
I have tried all the profiles you have, and none of them works for the latest database
[Image of Error](https://i.imgur.com/MaBRNMr.png)

Is it possible for you to create a new profile for the latest TDB?
[Link to Latest Release of TDB](https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.23011)

I have selected the TrinityCore 3.3.5a (2020-01) Profile [Because im running TC fresh built from the TrinityCore github 3.3.5 Tree]
I have entered a valid path to my DBC files
I have entered the settings for my World database, i know the settings are the correct as i use the same settings in HeidiSQL (Its not a mistype as it was copy pasted in)

**Comment by NotCoffee418** [comment]
Can you tell me what you were trying to create? Can you tell me any flags or special things you changed?


I've seen the error before, i remember it vaguely and it does have to do with profiles, but i can't seem to replicate it.
My guess it's something that goes in an addon table.


I'll already make the table more verbose and set up a new profile for the recent version until i get more info to verify.

**Comment by LegacyAngel2K9** [comment]
If you are available on discord we can discuss all there?
Mr.Angel#0001

**Comment by LegacyAngel2K9** [comment]
I had a 3.3.5a server which havent had any updates since 2014, then the app worked fine, then i downloaded the source from trinitycore from tree 3.3.5a let the server update the db with all the new files up to 2023, so if there is any changes in the db its from them, if you add me on discord i can give you access to the DB so you can check for yourself?

**Comment by NotCoffee418** [comment]
fixed in v1.1.5
